"""
Relay Hybridisation

Implements relay hybridisation technique for combining low-level heuristics.

From paper Section 3.2:
"We form 'new' heuristics by pairing up each low level heuristic and invoking
them successively. The technique of combining two heuristics is known as relay
hybridisation which applies the second low level heuristic to the solution
generated by the preceding low level heuristic."

Given n low level heuristics, this creates (n + n²) heuristics total.
"""
module RelayHybridisation

export create_relay_heuristics, RelayLLH, is_relay_heuristic

"""
    RelayLLH

A relay heuristic that applies two low-level heuristics in sequence.
"""
struct RelayLLH
    id::String
    first_llh_id::String
    second_llh_id::String
    description::String
end

"""
    is_relay_heuristic(llh_id::String)::Bool

Check if a heuristic ID represents a relay heuristic (contains '+').
"""
function is_relay_heuristic(llh_id::String)::Bool
    return occursin("+", llh_id)
end

"""
    create_relay_heuristics(base_llhs::Vector{String})::Vector{String}

Create all possible relay heuristic combinations.

From paper: Given n LLHs {LLH₁,...,LLHₙ}, we end up with (n+n²) LLHs:
{LLH₁,...,LLHₙ, LLH₁+LLH₁, LLH₁+LLH₂,..., LLHₙ+LLHₙ}

# Arguments
- `base_llhs`: Vector of base low-level heuristic IDs

# Returns
- Vector containing all single and paired heuristic IDs

# Example
```julia
base_llhs = ["swap", "2opt", "insert"]
all_llhs = create_relay_heuristics(base_llhs)
# Returns: ["swap", "2opt", "insert",
#           "swap+swap", "swap+2opt", "swap+insert",
#           "2opt+swap", "2opt+2opt", "2opt+insert",
#           "insert+swap", "insert+2opt", "insert+insert"]
```
"""
function create_relay_heuristics(base_llhs::Vector{String})::Vector{String}
    n = length(base_llhs)
    all_llhs = Vector{String}()

    # Add all single heuristics
    append!(all_llhs, base_llhs)

    # Add all pairs (n²combinations)
    for i in 1:n
        for j in 1:n
            relay_id = "$(base_llhs[i])+$(base_llhs[j])"
            push!(all_llhs, relay_id)
        end
    end

    return all_llhs
end

"""
    parse_relay_heuristic(relay_id::String)::Tuple{String, String}

Parse a relay heuristic ID into its two component heuristic IDs.

# Arguments
- `relay_id`: Relay heuristic ID in format "LLH1+LLH2"

# Returns
- Tuple of (first_llh_id, second_llh_id)

# Example
```julia
first, second = parse_relay_heuristic("swap+2opt")
# Returns: ("swap", "2opt")
```
"""
function parse_relay_heuristic(relay_id::String)::Tuple{String, String}
    parts = split(relay_id, '+')
    if length(parts) != 2
        error("Invalid relay heuristic ID: $relay_id")
    end
    return (String(parts[1]), String(parts[2]))
end

"""
    apply_relay_heuristic(
        relay_id::String,
        solution,
        llh_map::Dict{String, Any},
        intensity::Float64=0.0
    )

Apply a relay heuristic by applying two heuristics in sequence.

# Arguments
- `relay_id`: ID of the relay heuristic (format: "LLH1+LLH2")
- `solution`: Current solution
- `llh_map`: Dictionary mapping heuristic IDs to heuristic functions
- `intensity`: Intensity parameter for heuristics

# Returns
- Solution after applying both heuristics in sequence
"""
function apply_relay_heuristic(
    relay_id::String,
    solution,
    llh_map::Dict{String, Any},
    intensity::Float64=0.0
)
    first_id, second_id = parse_relay_heuristic(relay_id)

    # Apply first heuristic
    intermediate = llh_map[first_id](solution, intensity)

    # Apply second heuristic to result of first
    final = llh_map[second_id](intermediate, intensity)

    return final
end

"""
    get_relay_description(relay_id::String)::String

Get a human-readable description of a relay heuristic.
"""
function get_relay_description(relay_id::String)::String
    if !is_relay_heuristic(relay_id)
        return relay_id
    end

    first, second = parse_relay_heuristic(relay_id)
    return "Apply $first, then $second"
end

end # module
